(define (problem smart-garage-problem)
  (:domain smart-garage)
  (:init
    (vehicle-waiting-to-enter)
    (vehicle-waiting-to-leave)
    (entrance-gate-open)
    (exit-gate-open)
  )
  (:goal (and
    (not (fan-on))
    (not (light-on))
    (entrance-gate-open)
    (exit-gate-open)
  ))
)